version: "3"
services:
  nginx:
    image: nginx:stable-alpine
  node-mongo:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: